### ISSUE TITLE
java-prettier-formatter does not use .editorconfig

### ISSUE THREAD

**Issue by chalford** [mwpb/java-prettier-formatter#3]
Hi,

When using `prettier` on the command line with Java files, it uses the values found in my `.editorconfig` file (such as line length and indent size). However, when I use this extension in VSCode, it seems to ignore them.

**Comment by mwpb** [comment]
Hi chalford, I think that the new version (1.1.4) should take into account the `.editorconfig`. Please let me know if it works for you!

**Comment by chalford** [comment]
Fantastic, just tested and it works! Thank you so much!

**Comment by mwpb** [comment]
Ok, good to hear!
