### ISSUE TITLE
Formatting 'switch case' problems

### ISSUE THREAD

**Issue by 404-nut-pound** [mwpb/java-prettier-formatter#5]
I appreciate for this extension.

But need some enhancement for 'switch case' grammer.

```java
//formatting works
switch(someParam) {
	case "A": //some codes
		break;
	default:
		break;
}
```

```java
//formatting not works, on JDK 12
switch(someParam) {
	case "A" -> "AA";
	default -> null;
}
//this neither, on JDK 13
switch(someParam) {
	case "A": yield "AA"; //this line can be { } blocked. like case "A" -> { yield "AA"; }
	default: yield null;
}
```

If some java files have switch line like examples, formatting not works for entire lines in file.

I hope i can get a solution for this issue.

Thx.

**Comment by mwpb** [comment]
Hi, apologies for the late reaction. Indeed I no longer use Java day-to-day and I don't think this extension can handle the `->` form of the switch statement. That said I have updated the various dependencies and republished so you can have another go.

If things still don't work then I would contact `https://github.com/jhipster/prettier-java` instead. For this issue I'm happy to spend the small amount of time updating this extension to the latest version of the `prettier-plugin-java` if that will help. It would be more sustainable if this extension could somehow be moved into that project and I've mentioned that here https://github.com/jhipster/prettier-java/issues/501. Thanks,

**Comment by 404-nut-pound** [comment]
Many thanks. I tried formatting after update plugin, and it works so good.

Thank you for your support again.
